In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
data=pd.read_csv('data.csv')

In [4]:
# five elements from top
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
# any missing values
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [6]:
data['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [ ]:
#understand the distribution of fish species
plt.figure(figsize=(15,10))
sns.countplot(data['Species'])
plt.xlabel('Species')
plt.ylabel('Count')
plt.title('Countplot for Species')
plt.show()

In [8]:
# creating the class numeric values
enc={'Bream':1,'Roach':2,'Whitefish':3,'Parkki':4,'Perch':5,'Pike':6,'Smelt':7}
data['Species']=data['Species'].map(enc)

In [9]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0          1   242.0     23.2     25.4     30.0  11.5200  4.0200
1          1   290.0     24.0     26.3     31.2  12.4800  4.3056
2          1   340.0     23.9     26.5     31.1  12.3778  4.6961
3          1   363.0     26.3     29.0     33.5  12.7300  4.4555
4          1   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        7    12.2     11.5     12.2     13.4   2.0904  1.3936
155        7    13.4     11.7     12.4     13.5   2.4300  1.2690
156        7    12.2     12.1     13.0     13.8   2.2770  1.2558
157        7    19.7     13.2     14.3     15.2   2.8728  2.0672
158        7    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [11]:
#define x and y columns
y=data['Species']
x=data.drop('Species',axis=1)
print(y.shape,x.shape)

(159,) (159, 6)


In [12]:
#apply standad scaler for preprocessing data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
col=list(x.columns)
x[col]=sc.fit_transform(x[col])
x.head()

Weight   Length1   Length2   Length3    Height     Width
0 -0.438072 -0.305789 -0.282303 -0.106020  0.596579 -0.236529
1 -0.303562 -0.225507 -0.198054 -0.002337  0.821261 -0.066579
2 -0.163448 -0.235542 -0.179332 -0.010977  0.797341  0.165793
3 -0.098995  0.005302  0.054694  0.196390  0.879771  0.022621
4  0.088759  0.025372  0.054694  0.239592  0.812835  0.426371

In [13]:
from sklearn.model_selection import train_test_split as tts,GridSearchCV
xtrain,xtest,ytrain,ytest=tts(x,y,test_size=0.2,random_state=12)
print(xtrain.shape,ytrain.shape)
print(xtest.shape,ytest.shape)

(127, 6) (127,)
(32, 6) (32,)


In [14]:

from sklearn.linear_model import LogisticRegression
m1=LogisticRegression(max_iter=1000)
m1.fit(xtrain,ytrain)
ypred=m1.predict(xtest)
print("The accuracy score was found to be: ",accuracy_score(ytest,ypred)*100)
print("The confusion matrix of the model is:\n",confusion_matrix(ytest,ypred))

The accuracy score was found to be:  90.625
The confusion matrix of the model is:
 [[ 8  0  0  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  2]]


In [15]:
import pickle
filename_pkl = "model.pkl"  

with open(filename_pkl, 'wb') as file:  
    pickle.dump(m1, file)

In [16]:
# Load the Model back from file
with open(filename_pkl, 'rb') as file:  
   model_pkl = pickle.load(file)

model_pkl

LogisticRegression(max_iter=1000)

In [17]:
xtest

Weight   Length1   Length2   Length3    Height     Width
88  -0.751929 -0.626914 -0.600578 -0.667639 -0.669597 -0.531085
124  1.686065  1.360049  1.365240  1.207305  0.693192  1.701710
45  -0.667860 -0.576738 -0.553773 -0.512114 -0.453481 -0.355363
90  -0.807975 -0.626914 -0.600578 -0.667639 -0.807098 -0.251406
31   1.559962  0.878361  0.943993  1.103621  2.132841  1.115454
23   0.789331  0.557236  0.616357  0.809851  1.520723  1.019411
154 -1.082039 -1.479903 -1.517960 -1.540309 -1.610359 -1.799403
143  3.227325  2.985746  2.956616  2.831680  0.147215  1.027385
149 -1.088764 -1.560184 -1.611570 -1.626712 -1.612044 -1.868668
136  0.397011  1.390155  1.365240  1.259146 -0.277340  0.423753
87  -0.779952 -0.626914 -0.600578 -0.667639 -0.779598 -0.531085
78  -0.897648 -0.948039 -0.909493 -1.021892 -0.882764 -0.770062
111  1.237698  0.627482  0.616357  0.524721  0.589183  2.010251
40  -1.116227 -0.727266 -0.740994 -0.728122 -0.584125 -0.634269
97  -0.709894 -0.426211 -0.413358 -0.494834 -0.607576 -0.352566
86  -0.779952 -0.626914 -0.600578 -0.667639 -0.669597 -0.601005
16   0.845377  0.416743  0.429136  0.611124  1.378378  0.516464
21   0.803343  0.517095  0.522746  0.688887  1.643596  0.567044
112  0.803343  0.778009  0.756772  0.671606  0.447025  1.455830
142  3.367440  2.985746  2.956616  2.831680  0.147215  1.027385
39  -0.779952 -0.767406 -0.787799 -0.779963 -0.644789 -0.501808
85  -0.751929 -0.697160 -0.666106 -0.728122 -0.605469 -0.525730
66  -0.723906 -0.727266 -0.722272 -0.693560 -0.101433 -0.668307
38  -0.872427 -0.807547 -0.806521 -0.779963 -0.785074 -0.739595
5    0.144804  0.055477  0.120222  0.300074  1.083951  0.303431
6    0.284919  0.055477  0.120222  0.282793  1.219018  0.512358
61  -0.962101 -1.279200 -1.283934 -1.272460 -0.496990 -1.244268
1   -0.303562 -0.225507 -0.198054 -0.002337  0.821261 -0.066579
83  -0.793963 -0.727266 -0.694189 -0.754042 -0.714651 -0.660511
94  -0.695883 -0.526562 -0.506968 -0.581236 -0.878247 -0.470984
63  -0.864020 -0.998215 -1.003103 -0.987330 -0.366464 -1.038079
11   0.284919  0.246146  0.241915  0.429678  1.263931  0.236308

In [18]:
# Use the Reloaded Model to 
# Calculate the accuracy score and predict target values

# Calculate the Score 
score = model_pkl.score(xtest, ypred)  
# Print the Score
print("Test score: {0:.2f} %".format(100 * score))  

# Predict the Labels using the reloaded Model
Ypredict = model_pkl.predict(xtest)  

Ypredict

Test score: 100.00 %


array([5, 5, 5, 5, 1, 1, 7, 6, 7, 6, 5, 5, 5, 2, 5, 5, 1, 1, 5, 6, 5, 5,
       4, 5, 1, 1, 4, 1, 5, 5, 4, 1], dtype=int64)

In [19]:
#def ValuePredictor(to_predict_list):
to_predict_list=[12.2,	11.5,	12.2,	13.4,	2.0904,	1.3936]

    #return result[0]

In [20]:
to_predict = np.array(to_predict_list).reshape(1, 6)
to_predict


array([[12.2   , 11.5   , 12.2   , 13.4   ,  2.0904,  1.3936]])

In [21]:
loaded_model = pickle.load(open("model.pkl", "rb"))


In [22]:
result = loaded_model.predict(to_predict)
result[0]

c:\Users\gazmi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


6